// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnIaFNbzPqvqnjzxkzXf5YN7aPd-2Ovak',
    appId: '1:1083775861995:web:002281c157d7c78814eaae',
    messagingSenderId: '1083775861995',
    projectId: 'fir-bc611',
    authDomain: 'fir-bc611.firebaseapp.com',
    databaseURL: 'https://fir-bc611-default-rtdb.firebaseio.com',
    storageBucket: 'fir-bc611.firebasestorage.app',
    measurementId: 'G-MGTXGSY4M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHm0Uw0mpaYRgjasfj_yLmD4fFHkqNCUQ',
    appId: '1:1083775861995:android:fd07d03b19c7355a14eaae',
    messagingSenderId: '1083775861995',
    projectId: 'fir-bc611',
    databaseURL: 'https://fir-bc611-default-rtdb.firebaseio.com',
    storageBucket: 'fir-bc611.firebasestorage.app',
  );
}
